{% set version = "0.7.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wellknown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wellknown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wellknown/wellknown_{{ version }}.tar.gz
  sha256: 483e6fc43edf09ed583e74ce5ca7e2d7838ef8a32291e06d774c37546eed1a34

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win and r_base == "3.6"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-jsonlite
    - r-wk
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    #- r-bh
    - r-rcpp
    - r-jsonlite
    - r-wk

test:
  commands:
    - $R -e "library('wellknown')"           # [not win]
    - "\"%R%\" -e \"library('wellknown')\""  # [win]

about:
  home: https://docs.ropensci.org/wellknown/, https://github.com/ropensci/wellknown
  license: MIT
  summary: Convert 'WKT' to 'GeoJSON' and 'GeoJSON' to 'WKT'. Functions included for converting between 'GeoJSON' to 'WKT', creating both 'GeoJSON' features, and non-features, creating 'WKT' from R objects (e.g., lists, data.frames, vectors), and linting 'WKT'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
